const certificatesDatabase = [
  {
    id: "074/AIDA/CTF/IV/2025",
    name: "Agus Riyanto",
    course: "Competency Enhancement Training for Facilitators and Trainer",
    date: "28–30 April 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "075/AIDA/CTF/IV/2025",
    name: "Agus Supriyono",
    course: "Competency Enhancement Training for Facilitators and Trainer",
    date: "28–30 April 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "076/AIDA/CTF/IV/2025",
    name: "Anindya Dyah Safitri",
    course: "Competency Enhancement Training for Facilitators and Trainer",
    date: "28–30 April 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "077/AIDA/CTF/IV/2025",
    name: "Budi Mulia",
    course: "Competency Enhancement Training for Facilitators and Trainer",
    date: "28–30 April 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "078/AIDA/CTF/IV/2025",
    name: "Novi Fitriani",
    course: "Competency Enhancement Training for Facilitators and Trainer",
    date: "28–30 April 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "079/AIDA/CTF/IV/2025",
    name: "Ragil Triharso",
    course: "Competency Enhancement Training for Facilitators and Trainer",
    date: "28–30 April 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "080/AIDA/CTF/IV/2025",
    name: "Shindy Annissa",
    course: "Competency Enhancement Training for Facilitators and Trainer",
    date: "28–30 April 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "081/AIDA/CTF/IV/2025",
    name: "Sumirating Baskoro",
    course: "Competency Enhancement Training for Facilitators and Trainer",
    date: "28–30 April 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "082/AIDA/CTF/IV/2025",
    name: "Syopiyulloh Mas'ud",
    course: "Competency Enhancement Training for Facilitators and Trainer",
    date: "28–30 April 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "083/AIDA/CTF/IV/2025",
    name: "Togama Hany Sinaga",
    course: "Competency Enhancement Training for Facilitators and Trainer",
    date: "28–30 April 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "084/AIDA/CTF/IV/2025",
    name: "Yunita Weni Safitri",
    course: "Competency Enhancement Training for Facilitators and Trainer",
    date: "28–30 April 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "085/AIDA/CTF/IV/2025",
    name: "Anggraini Reknowati",
    course: "Competency Enhancement Training for Facilitators and Trainer",
    date: "28–30 April 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "086/AIDA/CTF/IV/2025",
    name: "Dita Dania Lee",
    course: "Competency Enhancement Training for Facilitators and Trainer",
    date: "28–30 April 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "087/AIDA/CTF/IV/2025",
    name: "Nyak Meutia Aguspita",
    course: "Competency Enhancement Training for Facilitators and Trainer",
    date: "28–30 April 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "088/AIDA/CTF/IV/2025",
    name: "Rudy Ibrahim",
    course: "Competency Enhancement Training for Facilitators and Trainer",
    date: "28–30 April 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "089/AIDA/CTF/IV/2025",
    name: "Widya Ayu Octavia",
    course: "Competency Enhancement Training for Facilitators and Trainer",
    date: "28–30 April 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "090/AIDA/CTF/IV/2025",
    name: "Yuddo Kristianto Yogi Agus Mahendrayana",
    course: "Competency Enhancement Training for Facilitators and Trainer",
    date: "28–30 April 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "091/AIDA/CTF/IV/2025",
    name: "A.A Diyah Ratnasari",
    course: "Competency Enhancement Training for Facilitators and Trainer",
    date: "28–30 April 2025",
    status: "Valid / Terverifikasi",
  },
];
