const certificatesDatabase = [
  {
    id: "074/AIDA/CTF/IV/2025",
    name: "Agus Riyanto",
    course: "Competency Enhancement Training for Facilitators and Trainer",
    date: "28–30 April 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "075/AIDA/CTF/IV/2025",
    name: "Agus Supriyono",
    course: "Competency Enhancement Training for Facilitators and Trainer",
    date: "28–30 April 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "076/AIDA/CTF/IV/2025",
    name: "Anindya Dyah Safitri",
    course: "Competency Enhancement Training for Facilitators and Trainer",
    date: "28–30 April 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "077/AIDA/CTF/IV/2025",
    name: "Budi Mulia",
    course: "Competency Enhancement Training for Facilitators and Trainer",
    date: "28–30 April 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "077/AIDA/CTF/IV/2025",
    name: "Ansor Arif Gunawan",
    course: "Competency Enhancement Training for Facilitators and Trainer",
    date: "28–30 April 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "078/AIDA/CTF/IV/2025",
    name: "Novi Fitriani",
    course: "Competency Enhancement Training for Facilitators and Trainer",
    date: "28–30 April 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "079/AIDA/CTF/IV/2025",
    name: "Ragil Triharso",
    course: "Competency Enhancement Training for Facilitators and Trainer",
    date: "28–30 April 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "080/AIDA/CTF/IV/2025",
    name: "Shindy Annissa",
    course: "Competency Enhancement Training for Facilitators and Trainer",
    date: "28–30 April 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "081/AIDA/CTF/IV/2025",
    name: "Sumirating Baskoro",
    course: "Competency Enhancement Training for Facilitators and Trainer",
    date: "28–30 April 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "082/AIDA/CTF/IV/2025",
    name: "Syopiyulloh Mas'ud",
    course: "Competency Enhancement Training for Facilitators and Trainer",
    date: "28–30 April 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "083/AIDA/CTF/IV/2025",
    name: "Togama Hany Sinaga",
    course: "Competency Enhancement Training for Facilitators and Trainer",
    date: "28–30 April 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "083/AIDA/CTF/IV/2025",
    name: "Yunita Weni Safitri",
    course: "Competency Enhancement Training for Facilitators and Trainer",
    date: "28–30 April 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "085/AIDA/CTF/IV/2025",
    name: "Anggraini Reknowati",
    course: "Competency Enhancement Training for Facilitators and Trainer",
    date: "28–30 April 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "086/AIDA/CTF/IV/2025",
    name: "Dita Dania Lee",
    course: "Competency Enhancement Training for Facilitators and Trainer",
    date: "28–30 April 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "087/AIDA/CTF/IV/2025",
    name: "Nyak Meutia Aguspita",
    course: "Competency Enhancement Training for Facilitators and Trainer",
    date: "28–30 April 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "088/AIDA/CTF/IV/2025",
    name: "Rudy Ibrahim",
    course: "Competency Enhancement Training for Facilitators and Trainer",
    date: "28–30 April 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "089/AIDA/CTF/IV/2025",
    name: "Widya Ayu Octavia",
    course: "Competency Enhancement Training for Facilitators and Trainer",
    date: "28–30 April 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "090/AIDA/CTF/IV/2025",
    name: "Yuddo Kristianto Yogi Agus Mahendrayana",
    course: "Competency Enhancement Training for Facilitators and Trainer",
    date: "28–30 April 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "091/AIDA/CTF/IV/2025",
    name: "A.A Diyah Ratnasari",
    course: "Competency Enhancement Training for Facilitators and Trainer",
    date: "28–30 April 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "092/AIDA/CTF/IV/2025",
    name: "Achmad Ismail",
    course: "Competency Enhancement Training for Facilitators and Trainer",
    date: "28–30 April 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "093/AIDA/CTF/IV/2025",
    name: "Adila Shifa Kanianingrat",
    course: "Competency Enhancement Training for Facilitators and Trainer",
    date: "28–30 April 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "094/AIDA/CTF/IV/2025",
    name: "Ahmad Fathoni Kamil",
    course: "Competency Enhancement Training for Facilitators and Trainer",
    date: "28–30 April 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "095/AIDA/CTF/IV/2025",
    name: "Aulia Arifaturrochmah",
    course: "Competency Enhancement Training for Facilitators and Trainer",
    date: "28–30 April 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "096/AIDA/CTF/IV/2025",
    name: "Bayu Putra Pradana",
    course: "Competency Enhancement Training for Facilitators and Trainer",
    date: "28–30 April 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "097/AIDA/CTF/IV/2025",
    name: "Budiyanto",
    course: "Competency Enhancement Training for Facilitators and Trainer",
    date: "28–30 April 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "098/AIDA/CTF/IV/2025",
    name: "Chandramurti Wicaksana Purwadisti",
    course: "Competency Enhancement Training for Facilitators and Trainer",
    date: "28–30 April 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "099/AIDA/CTF/IV/2025",
    name: "David Panahatan Pardede",
    course: "Competency Enhancement Training for Facilitators and Trainer",
    date: "28–30 April 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "100/AIDA/CTF/IV/2025",
    name: "Denden Sumarlin",
    course: "Competency Enhancement Training for Facilitators and Trainer",
    date: "28–30 April 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "101/AIDA/CTF/IV/2025",
    name: "Sudi Handayani",
    course: "Competency Enhancement Training for Facilitators and Trainer",
    date: "28–30 April 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "102/AIDA/CTF/IV/2025",
    name: "Sony Sandra",
    course: "Competency Enhancement Training for Facilitators and Trainer",
    date: "28–30 April 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "103/AIDA/CTF/IV/2025",
    name: "Eko Budi Purnomo",
    course: "Competency Enhancement Training for Facilitators and Trainer",
    date: "28–30 April 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "104/AIDA/CTF/IV/2025",
    name: "Fahrizal Ramadhan",
    course: "Competency Enhancement Training for Facilitators and Trainer",
    date: "28–30 April 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "105/AIDA/CTF/IV/2025",
    name: "Hastuti Susitoningsih",
    course: "Competency Enhancement Training for Facilitators and Trainer",
    date: "28–30 April 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "106/AIDA/CTF/IV/2025",
    name: "Irja Faily",
    course: "Competency Enhancement Training for Facilitators and Trainer",
    date: "28–30 April 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "107/AIDA/CTF/IV/2025",
    name: "Kristowiro Penna",
    course: "Competency Enhancement Training for Facilitators and Trainer",
    date: "28–30 April 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "108/AIDA/CTF/IV/2025",
    name: "La Hasiri",
    course: "Competency Enhancement Training for Facilitators and Trainer",
    date: "28–30 April 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "109/AIDA/CTF/IV/2025",
    name: "Lalik Mustikowati",
    course: "Competency Enhancement Training for Facilitators and Trainer",
    date: "28–30 April 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "110/AIDA/CTF/IV/2025",
    name: "Lilik Tiyarsa",
    course: "Competency Enhancement Training for Facilitators and Trainer",
    date: "28–30 April 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "111/AIDA/CTF/IV/2025",
    name: "M. Alwan Wijaya",
    course: "Competency Enhancement Training for Facilitators and Trainer",
    date: "28–30 April 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "112/AIDA/CTF/IV/2025",
    name: "Meilinda Kurniasari",
    course: "Competency Enhancement Training for Facilitators and Trainer",
    date: "28–30 April 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "113/AIDA/CTF/IV/2025",
    name: "Moch. Yanuar Siswanto",
    course: "Competency Enhancement Training for Facilitators and Trainer",
    date: "28–30 April 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "114/AIDA/CTF/IV/2025",
    name: "Nanang Rois Adnan",
    course: "Competency Enhancement Training for Facilitators and Trainer",
    date: "28–30 April 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "115/AIDA/CTF/IV/2025",
    name: "Okka Rodolfo Pakpahan",
    course: "Competency Enhancement Training for Facilitators and Trainer",
    date: "28–30 April 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "116/AIDA/CTF/IV/2025",
    name: "Purwati Rahayu Edarsasi",
    course: "Competency Enhancement Training for Facilitators and Trainer",
    date: "28–30 April 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "117/AIDA/CTF/IV/2025",
    name: "Reyhan Ahmad Almer",
    course: "Competency Enhancement Training for Facilitators and Trainer",
    date: "28–30 April 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "118/AIDA/CTF/IV/2025",
    name: "Reza Riastyo",
    course: "Competency Enhancement Training for Facilitators and Trainer",
    date: "28–30 April 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "119/AIDA/CTF/IV/2025",
    name: "Rimba Suryawan",
    course: "Competency Enhancement Training for Facilitators and Trainer",
    date: "28–30 April 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "120/AIDA/CTF/IV/2025",
    name: "Ririn Tius Eka Margareta",
    course: "Competency Enhancement Training for Facilitators and Trainer",
    date: "28–30 April 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "121/AIDA/CTF/IV/2025",
    name: "Rusendra Ichwan",
    course: "Competency Enhancement Training for Facilitators and Trainer",
    date: "28–30 April 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "122/AIDA/CTF/IV/2025",
    name: "Sugiman",
    course: "Competency Enhancement Training for Facilitators and Trainer",
    date: "28–30 April 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "123/AIDA/CTF/IV/2025",
    name: "Usman",
    course: "Competency Enhancement Training for Facilitators and Trainer",
    date: "28–30 April 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "124/AIDA/CTF/IV/2025",
    name: "Wibowo Abilowo",
    course: "Competency Enhancement Training for Facilitators and Trainer",
    date: "28–30 April 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "125/AIDA/CTF/IV/2025",
    name: "Wuri Astamala Dewi",
    course: "Competency Enhancement Training for Facilitators and Trainer",
    date: "28–30 April 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "126/AIDA/CTF/IV/2025",
    name: "Wuri Ayu Dwi Hartanti",
    course: "Competency Enhancement Training for Facilitators and Trainer",
    date: "28–30 April 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "127/AIDA/CTF/IV/2025",
    name: "Irsyad Ibrasma",
    course: "Competency Enhancement Training for Facilitators and Trainer",
    date: "28–30 April 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "128/AIDA/CTF/IV/2025",
    name: "Dina Widayanti",
    course: "Competency Enhancement Training for Facilitators and Trainer",
    date: "28–30 April 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "129/AIDA/CTF/IV/2025",
    name: "Narso",
    course: "Competency Enhancement Training for Facilitators and Trainer",
    date: "28–30 April 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "130/AIDA/CTF/IV/2025",
    name: "Sugiarto",
    course: "Competency Enhancement Training for Facilitators and Trainer",
    date: "28–30 April 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "131/AIDA/CTF/IV/2025",
    name: "Sugiarto",
    course: "Competency Enhancement Training for Facilitators and Trainer",
    date: "28–30 April 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "132/AIDA/CTF/VI/2025",
    name: "Ahda Megawati Hasunia",
    course: "Training International Certified Project Risk Manager (CPRM)",
    date: "16 - 18 Juni 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "133/AIDA/CTF/VI/2025",
    name: "Anugrah Esa",
    course: "Training International Certified Project Risk Manager (CPRM)",
    date: "16 - 18 Juni 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "134/AIDA/CTF/VI/2025",
    name: "Ariestia Prawitasari",
    course: "Training International Certified Project Risk Manager (CPRM)",
    date: "16 - 18 Juni 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "135/AIDA/CTF/VI/2025",
    name: "Rahman Setiyadi",
    course: "Training International Certified Project Risk Manager (CPRM)",
    date: "16 - 18 Juni 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "136/AIDA/CTF/VI/2025",
    name: "Thomas",
    course: "Training International Certified Project Risk Manager (CPRM)",
    date: "16 - 18 Juni 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "137/AIDA/CTF/VI/2025",
    name: "Yudi Irawan",
    course: "Training International Certified Project Risk Manager (CPRM)",
    date: "16 - 18 Juni 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "138/AIDA/CTF/VI/2025",
    name: "Khumaidi Usman",
    course:
      "Short Training: Creating Interactive E-Courses Aligned with How the Brain Works",
    date: "2025-06-21 00:00:00",
    status: "Valid / Terverifikasi",
  },
  {
    id: "139/AIDA/CTF/VI/2025",
    name: "Agus Krisdianto",
    course:
      "Short Training: Creating Interactive E-Courses Aligned with How the Brain Works",
    date: "2025-06-21 00:00:00",
    status: "Valid / Terverifikasi",
  },
  {
    id: "140/AIDA/CTF/VI/2025",
    name: "Lea Christina Br Ginting",
    course:
      "Short Training: Creating Interactive E-Courses Aligned with How the Brain Works",
    date: "2025-06-21 00:00:00",
    status: "Valid / Terverifikasi",
  },
  {
    id: "141/AIDA/CTF/VI/2025",
    name: "Alhidayatul Pratama",
    course:
      "Short Training: Creating Interactive E-Courses Aligned with How the Brain Works",
    date: "2025-06-21 00:00:00",
    status: "Valid / Terverifikasi",
  },
  {
    id: "142/AIDA/CTF/VI/2025",
    name: "Riska Tahier",
    course:
      "Short Training: Creating Interactive E-Courses Aligned with How the Brain Works",
    date: "2025-06-21 00:00:00",
    status: "Valid / Terverifikasi",
  },
  {
    id: "143/AIDA/CTF/VI/2025",
    name: "Utaryana",
    course:
      "Short Training: Creating Interactive E-Courses Aligned with How the Brain Works",
    date: "2025-06-21 00:00:00",
    status: "Valid / Terverifikasi",
  },
  {
    id: "144/AIDA/CTF/VI/2025",
    name: "Utaryana",
    course:
      "Short Training: Creating Interactive E-Courses Aligned with How the Brain Works",
    date: "2025-06-21 00:00:00",
    status: "Valid / Terverifikasi",
  },
  {
    id: "145/AIDA/CTF/VI/2025",
    name: "Deden Sjahadat",
    course:
      "Short Training: Creating Interactive E-Courses Aligned with How the Brain Works",
    date: "2025-06-21 00:00:00",
    status: "Valid / Terverifikasi",
  },
  {
    id: "146/AIDA/CTF/VI/2025",
    name: "M. Afiani Rizvi Kaluni",
    course:
      "Short Training: Creating Interactive E-Courses Aligned with How the Brain Works",
    date: "2025-06-21 00:00:00",
    status: "Valid / Terverifikasi",
  },
  {
    id: "147/AIDA/CTF/VI/2025",
    name: "Nashori",
    course:
      "Short Training: Creating Interactive E-Courses Aligned with How the Brain Works",
    date: "2025-06-21 00:00:00",
    status: "Valid / Terverifikasi",
  },
  {
    id: "148/AIDA/CTF/VI/2025",
    name: "Ocha Cutnyak",
    course:
      "Short Training: Creating Interactive E-Courses Aligned with How the Brain Works",
    date: "2025-06-21 00:00:00",
    status: "Valid / Terverifikasi",
  },
  {
    id: "149/AIDA/CTF/VI/2025",
    name: "Imran Ramdani",
    course:
      "Short Training: Creating Interactive E-Courses Aligned with How the Brain Works",
    date: "2025-06-21 00:00:00",
    status: "Valid / Terverifikasi",
  },
  {
    id: "150/AIDA/CTF/VI/2025",
    name: "Arhamarifuddin",
    course:
      "Short Training: Creating Interactive E-Courses Aligned with How the Brain Works",
    date: "2025-06-21 00:00:00",
    status: "Valid / Terverifikasi",
  },
  {
    id: "151/AIDA/CTF/VI/2025",
    name: "Firdaus",
    course:
      "Short Training: Creating Interactive E-Courses Aligned with How the Brain Works",
    date: "2025-06-21 00:00:00",
    status: "Valid / Terverifikasi",
  },
  {
    id: "152/AIDA/CTF/IV/2025",
    name: "Rachmat Priyatna",
    course:
      "Short Training: Creating Interactive E-Courses Aligned with How the Brain Works",
    date: "2025-06-21 00:00:00",
    status: "Valid / Terverifikasi",
  },
  {
    id: "153/AIDA/CTF/IV/2025",
    name: "Aryanti Sukma Utami",
    course:
      "Short Training: Creating Interactive E-Courses Aligned with How the Brain Works",
    date: "2025-06-21 00:00:00",
    status: "Valid / Terverifikasi",
  },
  {
    id: "154/AIDA/CTF/IV/2025",
    name: "Decy Chalid",
    course:
      "Short Training: Creating Interactive E-Courses Aligned with How the Brain Works",
    date: "2025-06-21 00:00:00",
    status: "Valid / Terverifikasi",
  },
  {
    id: "155/AIDA/CTF/IV/2025",
    name: "Nailul Fajriah",
    course:
      "Short Training: Creating Interactive E-Courses Aligned with How the Brain Works",
    date: "2025-06-21 00:00:00",
    status: "Valid / Terverifikasi",
  },
  {
    id: "156/AIDA/CTF/IV/2025",
    name: "Sandrina Putri Shavira",
    course:
      "Short Training: Creating Interactive E-Courses Aligned with How the Brain Works",
    date: "2025-06-21 00:00:00",
    status: "Valid / Terverifikasi",
  },
  {
    id: "157/AIDA/CTF/VII/2025",
    name: "Rina Zulelli",
    course:
      "Webinar: Sharing Experiences in the Implementation of Risk Culture and Risk Management Programs for National Development",
    date: "2025-07-26 00:00:00",
    status: "Valid / Terverifikasi",
  },
  {
    id: "158/AIDA/CTF/VII/2025",
    name: "Frisca Amelia Savira",
    course:
      "Webinar: Sharing Experiences in the Implementation of Risk Culture and Risk Management Programs for National Development",
    date: "2025-07-26 00:00:00",
    status: "Valid / Terverifikasi",
  },
  {
    id: "159/AIDA/CTF/VII/2025",
    name: "Ridha Fitryani",
    course:
      "Webinar: Sharing Experiences in the Implementation of Risk Culture and Risk Management Programs for National Development",
    date: "2025-07-26 00:00:00",
    status: "Valid / Terverifikasi",
  },
  {
    id: "160/AIDA/CTF/VII/2025",
    name: "M. Rizki Aviansyah",
    course:
      "Webinar: Sharing Experiences in the Implementation of Risk Culture and Risk Management Programs for National Development",
    date: "2025-07-26 00:00:00",
    status: "Valid / Terverifikasi",
  },
  {
    id: "161/AIDA/CTF/VII/2025",
    name: "M. Fikri Fauzi Syahrir",
    course:
      "Webinar: Sharing Experiences in the Implementation of Risk Culture and Risk Management Programs for National Development",
    date: "2025-07-26 00:00:00",
    status: "Valid / Terverifikasi",
  },
  {
    id: "162/AIDA/CTF/VII/2025",
    name: "Risti Amalia Hersari Putri",
    course:
      "Webinar: Sharing Experiences in the Implementation of Risk Culture and Risk Management Programs for National Development",
    date: "2025-07-26 00:00:00",
    status: "Valid / Terverifikasi",
  },
  {
    id: "163/AIDA/CTF/VII/2025",
    name: "Paryanto",
    course:
      "Webinar: Sharing Experiences in the Implementation of Risk Culture and Risk Management Programs for National Development",
    date: "2025-07-26 00:00:00",
    status: "Valid / Terverifikasi",
  },
  {
    id: "164/AIDA/CTF/VIII/2025",
    name: "Marvell Christian Siregar",
    course:
      "Short Training: Teknik Akurat dalam Identifikasi Risiko Menggunakan Fault Tree Analysis (FTA)",
    date: "2025-08-15 00:00:00",
    status: "Valid / Terverifikasi",
  },
  {
    id: "165/AIDA/CTF/VIII/2025",
    name: "Febrian Davin Christabello Simanjuntak",
    course:
      "Short Training: Teknik Akurat dalam Identifikasi Risiko Menggunakan Fault Tree Analysis (FTA)",
    date: "2025-08-15 00:00:00",
    status: "Valid / Terverifikasi",
  },
  {
    id: "166/AIDA/CTF/VIII/2025",
    name: "Krisna Hanjar Prastawa",
    course:
      "Short Training: Teknik Akurat dalam Identifikasi Risiko Menggunakan Fault Tree Analysis (FTA)",
    date: "2025-08-15 00:00:00",
    status: "Valid / Terverifikasi",
  },
  {
    id: "167/AIDA/CTF/VIII/2025",
    name: "Ahmad Sapta Yudha",
    course:
      "Short Training: Teknik Akurat dalam Identifikasi Risiko Menggunakan Fault Tree Analysis (FTA)",
    date: "2025-08-15 00:00:00",
    status: "Valid / Terverifikasi",
  },
  {
    id: "168/AIDA/CTF/VIII/2025",
    name: "Bigjun",
    course:
      "Short Training: Teknik Akurat dalam Identifikasi Risiko Menggunakan Fault Tree Analysis (FTA)",
    date: "2025-08-15 00:00:00",
    status: "Valid / Terverifikasi",
  },
  {
    id: "169/AIDA/CTF/VIII/2025",
    name: "Philipus Joechayden",
    course:
      "Short Training: Teknik Akurat dalam Identifikasi Risiko Menggunakan Fault Tree Analysis (FTA)",
    date: "2025-08-15 00:00:00",
    status: "Valid / Terverifikasi",
  },
  {
    id: "170/AIDA/CTF/VIII/2025",
    name: "Adi Wirawan SE",
    course:
      "Short Training: Teknik Akurat dalam Identifikasi Risiko Menggunakan Fault Tree Analysis (FTA)",
    date: "2025-08-15 00:00:00",
    status: "Valid / Terverifikasi",
  },
  {
    id: "171/AIDA/CTF/VIII/2025",
    name: "Daud Daniel Verdritoniar",
    course:
      "Short Training: Teknik Akurat dalam Identifikasi Risiko Menggunakan Fault Tree Analysis (FTA)",
    date: "2025-08-15 00:00:00",
    status: "Valid / Terverifikasi",
  },
  {
    id: "172/AIDA/CTF/VIII/2025",
    name: "Dwi Purnomo Sakti",
    course:
      "Short Training: Teknik Akurat dalam Identifikasi Risiko Menggunakan Fault Tree Analysis (FTA)",
    date: "2025-08-15 00:00:00",
    status: "Valid / Terverifikasi",
  },
  {
    id: "173/AIDA/MRM/X/2025",
    name: "Willy Januardi",
    course: "MASTERING RISK MODEL “Boost Your Organization's Performance”",
    date: "20-21 Okt 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "174/AIDA/MRM/X/2025",
    name: "Diah Sri Kemala Bellina",
    course: "MASTERING RISK MODEL “Boost Your Organization's Performance”",
    date: "20-21 Okt 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "175/AIDA/MRM/X/2025",
    name: "Petra Safira",
    course: "MASTERING RISK MODEL “Boost Your Organization's Performance”",
    date: "20-21 Okt 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "176/AIDA/MRM/X/2025",
    name: "Rizki Budhisaputra Syafruddin",
    course: "MASTERING RISK MODEL “Boost Your Organization's Performance”",
    date: "20-21 Okt 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "177/AIDA/MRM/X/2025",
    name: "Tsauroya Rumaisha",
    course: "MASTERING RISK MODEL “Boost Your Organization's Performance”",
    date: "20-21 Okt 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "178/AIDA/MRM/X/2025",
    name: "Azhar Fuadi",
    course: "MASTERING RISK MODEL “Boost Your Organization's Performance”",
    date: "20-21 Okt 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "179/AIDA/MRM/X/2025",
    name: "Vina Novita",
    course: "MASTERING RISK MODEL “Boost Your Organization's Performance”",
    date: "20-21 Okt 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "180/AIDA/MRM/X/2025",
    name: "Zahra Putri Fauziyah",
    course: "MASTERING RISK MODEL “Boost Your Organization's Performance”",
    date: "20-21 Okt 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "173/AIDA/MRM/X/2025",
    name: "Willy Januardi",
    course: "MASTERING RISK MODEL “Boost Your Organization's Performance”",
    date: "20-21 Okt 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "174/AIDA/MRM/X/2025",
    name: "Diah Sri Kemala Bellina",
    course: "MASTERING RISK MODEL “Boost Your Organization's Performance”",
    date: "20-21 Okt 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "175/AIDA/MRM/X/2025",
    name: "Petra Safira",
    course: "MASTERING RISK MODEL “Boost Your Organization's Performance”",
    date: "20-21 Okt 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "176/AIDA/MRM/X/2025",
    name: "Rizki Budhisaputra Syafruddin",
    course: "MASTERING RISK MODEL “Boost Your Organization's Performance”",
    date: "20-21 Okt 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "177/AIDA/MRM/X/2025",
    name: "Tsauroya Rumaisha",
    course: "MASTERING RISK MODEL “Boost Your Organization's Performance”",
    date: "20-21 Okt 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "178/AIDA/MRM/X/2025",
    name: "Azhar Fuadi",
    course: "MASTERING RISK MODEL “Boost Your Organization's Performance”",
    date: "20-21 Okt 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "179/AIDA/MRM/X/2025",
    name: "Vina Novita",
    course: "MASTERING RISK MODEL “Boost Your Organization's Performance”",
    date: "20-21 Okt 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "180/AIDA/MRM/X/2025",
    name: "Zahra Putri Fauziyah",
    course: "MASTERING RISK MODEL “Boost Your Organization's Performance”",
    date: "20-21 Okt 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "181/AIDA/MRM/X/2025",
    name: "Dewi Kurniawati",
    course: "MASTERING RISK MODEL “Boost Your Organization's Performance”",
    date: "20-21 Okt 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "182/AIDA/MRM/X/2025",
    name: "Fajar Hidayat",
    course: "MASTERING RISK MODEL “Boost Your Organization's Performance”",
    date: "20-21 Okt 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "183/AIDA/MRM/X/2025",
    name: "Gilang Ramadhan",
    course: "MASTERING RISK MODEL “Boost Your Organization's Performance”",
    date: "20-21 Okt 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "184/AIDA/MRM/X/2025",
    name: "Heri Kurniawan",
    course: "MASTERING RISK MODEL “Boost Your Organization's Performance”",
    date: "20-21 Okt 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "185/AIDA/MRM/X/2025",
    name: "Irfan Maulana",
    course: "MASTERING RISK MODEL “Boost Your Organization's Performance”",
    date: "20-21 Okt 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "186/AIDA/MRM/X/2025",
    name: "Joko Susanto",
    course: "MASTERING RISK MODEL “Boost Your Organization's Performance”",
    date: "20-21 Okt 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "187/AIDA/MRM/X/2025",
    name: "Kurniawan",
    course: "MASTERING RISK MODEL “Boost Your Organization's Performance”",
    date: "20-21 Okt 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "188/AIDA/MRM/X/2025",
    name: "Lina Marlina",
    course: "MASTERING RISK MODEL “Boost Your Organization's Performance”",
    date: "20-21 Okt 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "189/AIDA/MRM/X/2025",
    name: "Maya Sari",
    course: "MASTERING RISK MODEL “Boost Your Organization's Performance”",
    date: "20-21 Okt 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "190/AIDA/MRM/X/2025",
    name: "Nanda Pratama",
    course: "MASTERING RISK MODEL “Boost Your Organization's Performance”",
    date: "20-21 Okt 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "191/AIDA/MRM/X/2025",
    name: "Oki Setiawan",
    course: "MASTERING RISK MODEL “Boost Your Organization's Performance”",
    date: "20-21 Okt 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "192/AIDA/MRM/X/2025",
    name: "Putri Amelia",
    course: "MASTERING RISK MODEL “Boost Your Organization's Performance”",
    date: "20-21 Okt 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "193/AIDA/MRM/X/2025",
    name: "Rani Anggraini",
    course: "MASTERING RISK MODEL “Boost Your Organization's Performance”",
    date: "20-21 Okt 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "194/AIDA/MRM/X/2025",
    name: "Sari Wulandari",
    course: "MASTERING RISK MODEL “Boost Your Organization's Performance”",
    date: "20-21 Okt 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "195/AIDA/MRM/X/2025",
    name: "Taufik Hidayat",
    course: "MASTERING RISK MODEL “Boost Your Organization's Performance”",
    date: "20-21 Okt 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "196/AIDA/MRM/X/2025",
    name: "Umar Faruq",
    course: "MASTERING RISK MODEL “Boost Your Organization's Performance”",
    date: "20-21 Okt 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "197/AIDA/MRM/X/2025",
    name: "Vicky Pratama",
    course: "MASTERING RISK MODEL “Boost Your Organization's Performance”",
    date: "20-21 Okt 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "198/AIDA/MRM/X/2025",
    name: "Wahyu Setiawan",
    course: "MASTERING RISK MODEL “Boost Your Organization's Performance”",
    date: "20-21 Okt 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "199/AIDA/MRM/X/2025",
    name: "Yuni Astuti",
    course: "MASTERING RISK MODEL “Boost Your Organization's Performance”",
    date: "20-21 Okt 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "200/AIDA/MRM/X/2025",
    name: "Zainal Abidin",
    course: "MASTERING RISK MODEL “Boost Your Organization's Performance”",
    date: "20-21 Okt 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "201/AIDA/MRM/X/2025",
    name: "Aditia Nugraha",
    course: "MASTERING RISK MODEL “Boost Your Organization's Performance”",
    date: "20-21 Okt 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "202/AIDA/MRM/X/2025",
    name: "Bambang Suryono",
    course: "MASTERING RISK MODEL “Boost Your Organization's Performance”",
    date: "20-21 Okt 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "203/AIDA/MRM/X/2025",
    name: "Citra Lestari",
    course: "MASTERING RISK MODEL “Boost Your Organization's Performance”",
    date: "20-21 Okt 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "204/AIDA/MRM/X/2025",
    name: "Dimas Saputra",
    course: "MASTERING RISK MODEL “Boost Your Organization's Performance”",
    date: "20-21 Okt 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "205/AIDA/MRM/X/2025",
    name: "Eka Putri",
    course: "MASTERING RISK MODEL “Boost Your Organization's Performance”",
    date: "20-21 Okt 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "206/AIDA/MRM/X/2025",
    name: "Fikri Ramadhan",
    course: "MASTERING RISK MODEL “Boost Your Organization's Performance”",
    date: "20-21 Okt 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "207/AIDA/MRM/X/2025",
    name: "Gita Permata Sari",
    course: "MASTERING RISK MODEL “Boost Your Organization's Performance”",
    date: "20-21 Okt 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "208/AIDA/MRM/X/2025",
    name: "Hana Safitri",
    course: "MASTERING RISK MODEL “Boost Your Organization's Performance”",
    date: "20-21 Okt 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "209/AIDA/MRM/X/2025",
    name: "Indra Gunawan",
    course: "MASTERING RISK MODEL “Boost Your Organization's Performance”",
    date: "20-21 Okt 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "210/AIDA/MRM/X/2025",
    name: "Jihan Rahmawati",
    course: "MASTERING RISK MODEL “Boost Your Organization's Performance”",
    date: "20-21 Okt 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "211/AIDA/MRM/X/2025",
    name: "Kiki Amelia",
    course: "MASTERING RISK MODEL “Boost Your Organization's Performance”",
    date: "20-21 Okt 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "212/AIDA/MRM/X/2025",
    name: "Lukman Hakim",
    course: "MASTERING RISK MODEL “Boost Your Organization's Performance”",
    date: "20-21 Okt 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "213/AIDA/MRM/X/2025",
    name: "Miftahul Huda",
    course: "MASTERING RISK MODEL “Boost Your Organization's Performance”",
    date: "20-21 Okt 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "214/AIDA/MRM/X/2025",
    name: "Nia Kurnia",
    course: "MASTERING RISK MODEL “Boost Your Organization's Performance”",
    date: "20-21 Okt 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "215/AIDA/MRM/X/2025",
    name: "Oktavia Sari",
    course: "MASTERING RISK MODEL “Boost Your Organization's Performance”",
    date: "20-21 Okt 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "216/AIDA/MRM/X/2025",
    name: "Prasetyo Nugroho",
    course: "MASTERING RISK MODEL “Boost Your Organization's Performance”",
    date: "20-21 Okt 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "217/AIDA/MRM/X/2025",
    name: "Qori Rahma",
    course: "MASTERING RISK MODEL “Boost Your Organization's Performance”",
    date: "20-21 Okt 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "218/AIDA/MRM/X/2025",
    name: "Rizal Fahmi",
    course: "MASTERING RISK MODEL “Boost Your Organization's Performance”",
    date: "20-21 Okt 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "219/AIDA/MRM/X/2025",
    name: "Siti Nurhaliza",
    course: "MASTERING RISK MODEL “Boost Your Organization's Performance”",
    date: "20-21 Okt 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "220/AIDA/MRM/X/2025",
    name: "Teguh Santoso",
    course: "MASTERING RISK MODEL “Boost Your Organization's Performance”",
    date: "20-21 Okt 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "214/AIDA/BCMS/X/2025",
    name: "Aldian Eka W.",
    course: "Business Continuity Management System (BCMS)",
    date: "29-31 Okt 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "215/AIDA/BCMS/X/2025",
    name: "Silo Pinarseto",
    course: "Business Continuity Management System (BCMS)",
    date: "29-31 Okt 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "216/AIDA/BCMS/X/2025",
    name: "Muchammad Bintoro",
    course: "Business Continuity Management System (BCMS)",
    date: "29-31 Okt 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "217/AIDA/BCMS/X/2025",
    name: "Wildan K.",
    course: "Business Continuity Management System (BCMS)",
    date: "29-31 Okt 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "218/AIDA/BCMS/X/2025",
    name: "Wedi Septiadi",
    course: "Business Continuity Management System (BCMS)",
    date: "29-31 Okt 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "219/AIDA/BCMS/X/2025",
    name: "Ofi Syofiyah",
    course: "Business Continuity Management System (BCMS)",
    date: "29-31 Okt 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "220/AIDA/BCMS/X/2025",
    name: "Miftahudin Zakariya",
    course: "Business Continuity Management System (BCMS)",
    date: "29-31 Okt 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "221/AIDA/BCMS/X/2025",
    name: "Surya Marta K",
    course: "Business Continuity Management System (BCMS)",
    date: "29-31 Okt 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "222/AIDA/BCMS/X/2025",
    name: "Suhendra",
    course: "Business Continuity Management System (BCMS)",
    date: "29-31 Okt 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "223/AIDA/BCMS/X/2025",
    name: "M. Wahyu Dzikri",
    course: "Business Continuity Management System (BCMS)",
    date: "29-31 Okt 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "224/AIDA/BCMS/X/2025",
    name: "Fahrul Dwi Nugraha",
    course: "Business Continuity Management System (BCMS)",
    date: "29-31 Okt 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "225/AIDA/BCMS/X/2025",
    name: "Wisardi Rizqi",
    course: "Business Continuity Management System (BCMS)",
    date: "29-31 Okt 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "226/AIDA/BCMS/X/2025",
    name: "Andre Marta",
    course: "Business Continuity Management System (BCMS)",
    date: "29-31 Okt 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "227/AIDA/BCMS/X/2025",
    name: "Abdul Ghoni",
    course: "Managing People",
    date: "11-12 Des 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "228/AIDA/BCMS/X/2026",
    name: "Aisyah Nur Rizki",
    course: "Managing People",
    date: "11-12 Des 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "229/AIDA/BCMS/X/2027",
    name: "Cecilia Ayu Anggraini",
    course: "Managing People",
    date: "11-12 Des 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "230/AIDA/BCMS/X/2028",
    name: "Daniel Agus Supriono",
    course: "Managing People",
    date: "11-12 Des 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "231/AIDA/BCMS/X/2029",
    name: "Destiana Purbandari",
    course: "Managing People",
    date: "11-12 Des 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "232/AIDA/BCMS/X/2030",
    name: "Edlyn Sabella",
    course: "Managing People",
    date: "11-12 Des 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "233/AIDA/BCMS/X/2031",
    name: "Hamzah Fathurrohman",
    course: "Managing People",
    date: "11-12 Des 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "234/AIDA/BCMS/X/2032",
    name: "Jovanka Romana Uli Simanjuntak",
    course: "Managing People",
    date: "11-12 Des 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "235/AIDA/BCMS/X/2033",
    name: "Leticia Annalisa",
    course: "Managing People",
    date: "11-12 Des 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "236/AIDA/BCMS/X/2034",
    name: "Lukas Eko Widyasmoro",
    course: "Managing People",
    date: "11-12 Des 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "237/AIDA/BCMS/X/2035",
    name: "Siwiek Tri Arima",
    course: "Managing People",
    date: "11-12 Des 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "238/AIDA/BCMS/X/2036",
    name: "Sriyana",
    course: "Managing People",
    date: "11-12 Des 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "239/AIDA/BCMS/X/2037",
    name: "Widhi Hastuti",
    course: "Managing People",
    date: "11-12 Des 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "240/AIDA/BCMS/X/2037",
    name: "Yohana Irma Gunawan",
    course: "Managing People",
    date: "11-12 Des 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "241/AIDA/BCMS/X/2037",
    name: "Yuli Wiyatno",
    course: "Managing People",
    date: "11-12 Des 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "242/AIDA/BCMS/X/2025",
    name: "Nike Angelia Ovier Goretti",
    course: "Business Continuity Management System (BCMS)",
    date: "29-31 Okt 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "243/AIDA/BCMS/X/2025",
    name: "Denyus Mardony",
    course: "Business Continuity Management System (BCMS)",
    date: "29-31 Okt 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "244/AIDA/BCMS/X/2025",
    name: "Anggiawan Novtiano",
    course: "Business Continuity Management System (BCMS)",
    date: "29-31 Okt 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "245/AIDA/BCMS/X/2025",
    name: "Sahat Farel Hasibuan",
    course: "Business Continuity Management System (BCMS)",
    date: "29-31 Okt 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "246/AIDA/BCMS/X/2025",
    name: "Bunayya Ahmad Lazuardi",
    course: "Business Continuity Management System (BCMS)",
    date: "29-31 Okt 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "247/AIDA/BCMS/X/2025",
    name: "Muhammad Zakka Pradipta",
    course: "Business Continuity Management System (BCMS)",
    date: "29-31 Okt 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "248/AIDA/BCMS/X/2025",
    name: "Yudha Suryoraino",
    course: "Business Continuity Management System (BCMS)",
    date: "29-31 Okt 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "249/AIDA/BCMS/X/2025",
    name: "Novia Dwi Fazriati",
    course: "Business Continuity Management System (BCMS)",
    date: "29-31 Okt 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "250/AIDA/BCMS/X/2025",
    name: "Dian Fitria Utami",
    course: "Business Continuity Management System (BCMS)",
    date: "29-31 Okt 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "251/AIDA/MRM/X/2025",
    name: "Nike Angelia Ovier Goretti",
    course: "MASTERING RISK MODEL “Boost Your Organization's Performance”",
    date: "20-21 Okt 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "252/AIDA/MRM/X/2025",
    name: "Denyus Mardony",
    course: "MASTERING RISK MODEL “Boost Your Organization's Performance”",
    date: "20-21 Okt 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "253/AIDA/MRM/X/2025",
    name: "Anggiawan Novtiano",
    course: "MASTERING RISK MODEL “Boost Your Organization's Performance”",
    date: "20-21 Okt 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "254/AIDA/MRM/X/2025",
    name: "Sahat Farel Hasibuan",
    course: "MASTERING RISK MODEL “Boost Your Organization's Performance”",
    date: "20–21 Oktober 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "255/AIDA/MRM/X/2025",
    name: "Bunayya Ahmad Lazuardi",
    course: "MASTERING RISK MODEL “Boost Your Organization's Performance”",
    date: "20–21 Oktober 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "256/AIDA/MRM/X/2025",
    name: "Muhammad Zakka Pradipta",
    course: "MASTERING RISK MODEL “Boost Your Organization's Performance”",
    date: "20–21 Oktober 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "257/AIDA/MRM/X/2025",
    name: "Yudha Suryoraino",
    course: "MASTERING RISK MODEL “Boost Your Organization's Performance”",
    date: "20–21 Oktober 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "258/AIDA/MRM/X/2025",
    name: "Novia Dwi Fazriati",
    course: "MASTERING RISK MODEL “Boost Your Organization's Performance”",
    date: "20–21 Oktober 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "259/AIDA/MRM/X/2025",
    name: "Dian Fitria Utami",
    course: "MASTERING RISK MODEL “Boost Your Organization's Performance”",
    date: "20–21 Oktober 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "260/AIDA/CABMS/XII/2025",
    name: "Dana Kristina",
    course: "Training: International Certified Anti Bribery Management System",
    date: "02–03 Desember 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "2024501120251701",
    name: "Dana Kristina",
    course: "Training: International Certified Anti Bribery Management System",
    date: "02–03 Desember 2025",
    status: "Valid / Terverifikasi",
  },
  {
    id: "151515",
    name: "halo awkoaowk",
    course: "materi awkoak",
    date: "12122004",
    status: "Valid / Terverifikasi",
  },
  {
    id: "181818",
    name: "suhadi",
    course: "suhadi aawkowk",
    date: "123456",
    status: "Valid / Terverifikasi",
  },
];
